# workflows/rules/chip_cr/heatmap.smk
import os

# --- CONFIGURATION ---
DEEPTOOLS_DIR = config["deeptools_dir"]
BIGWIG_DIR = config["bigwig_dir"]
SUBTRACTED_BIGWIG_DIR = config["subtracted_bigwig_dir"]
SAMPLES_INFO = config['samples_info']


# --- HEATMAP INPUT SELECTION ---

def get_heatmap_input_bigwigs(wildcards):
    """
    Determines the correct bigWig file for each sample for heatmap generation.
    Uses the subtracted bigWig if available, otherwise the normal bigWig.
    Excludes input samples.
    """
    bws = []
    subtracted_samples = {pair['sample'] for pair in config.get('subtraction_pairs', [])}

    for sample, info in SAMPLES_INFO.items():
        if 'input' not in sample:
            read_type = 'pe' if info['type'] == 'PE' else 'se'
            if sample in subtracted_samples:
                bws.append(os.path.join(SUBTRACTED_BIGWIG_DIR, f"{sample}_{read_type}.subtracted.bw"))
            else:
                bws.append(os.path.join(BIGWIG_DIR, f"{sample}_{read_type}.bw"))
    return bws


# --- MATRIX AND HEATMAP ---

rule computeMatrix:
    """
    Generates a matrix of scores for heatmap plotting.
    """
    input:
        bws = get_heatmap_input_bigwigs,
        bed = config["gene_bed"]
    output:
        matrix = os.path.join(DEEPTOOLS_DIR, "matrix.gz")
    params:
        extra = config.get("deeptools", {}).get("computeMatrix", {}).get("extra_args", ""),
        before_start_len=config.get("deeptools", {}).get("computeMatrix", {}).get("beforeRegionStartLength", 3000),
        region_body_len=config.get("deeptools", {}).get("computeMatrix", {}).get("regionBodyLength", 5000),
        after_start_len=config.get("deeptools", {}).get("computeMatrix", {}).get("afterRegionStartLength", 3000),
        skip_zeros="--skipZeros" if config.get("deeptools", {}).get("computeMatrix", {}).get("skipZeros", True) else ""
    threads: 8
    log:
        os.path.join("logs", config["pipeline"], "deeptools", "computeMatrix.log")
    shell:
        """
        pixi run computeMatrix scale-regions \\
            -S {input.bws} \\
            -R {input.bed} \\
            -o {output.matrix} \\
            --beforeRegionStartLength {params.before_start_len} \\
            --regionBodyLength {params.region_body_len} \\
            --afterRegionStartLength {params.after_start_len} \\
            {params.skip_zeros} \\
            -p {threads} {params.extra} > {log}.out 2> {log}.err
        """


rule plotHeatmap:
    """
    Plots a heatmap from the matrix generated by computeMatrix.
    """
    input:
        matrix = os.path.join(DEEPTOOLS_DIR, "matrix.gz")
    output:
        heatmap = os.path.join(DEEPTOOLS_DIR, "heatmap.png")
    params:
        extra = config.get("deeptools", {}).get("plotHeatmap", {}).get("extra_args", "")
    threads: 1
    log:
        os.path.join("logs", config["pipeline"], "deeptools", "plotHeatmap.log")
    shell:
        """
        pixi run plotHeatmap \\
            -m {input.matrix} \\
            -o {output.heatmap} \\
            {params.extra} > {log}.out 2> {log}.err
        """
