pipeline: "rnaseq"

rnaseq:
  raw_fastqs_dir: "/mnt/nas/jlgaralc/TFM_UOC/zzz/opt/RNAseq_data/AGR_RNAseq_Aug21_24hpfZFinjectedCTAmRNA_GON9692/merged_fastqs"
  samples_info: null
  qc_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/qc_raw"
  trimmed_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/trimmed_fastqs"
  qc_trimmed_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/qc_trimmed"
  transcriptome_fasta: "/home/jlgaralc/genomes/DanRer11/cdna/release_115/Danio_rerio.GRCz11.cdna.all.fa"
  kallisto_index: "/home/jlgaralc/genomes/DanRer11/cdna/release_115/kallisto.idx"
  kallisto_output_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/kallisto"
  kallisto:
    extra_args: "--bootstrap-samples=100"
  ref_genome: "/home/jlgaralc/genomes/DanRer11/assembly/release115/Danio_rerio.GRCz11.dna.primary_assembly.fa"
  hisat2_index_dir: "/home/jlgaralc/genomes/DanRer11/assembly/release115/"
  alignment_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/aligned_bams"
  marked_bam_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/marked_bams"
  duplication_qc_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/duplication_qc"
  bigwig_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/bigwigs"
  deeptools_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/deeptools"
  gene_body_coverage_dir: "/home/jlgaralc/CTA/rnaseq/Aug21/gene_body_coverage"
  multiqc_results_dir: "/home/jlgaralc/CTA/rnaseq/Aug21"
  hisat2:
    extra_args: ""
  fastp:
    extra_args: "-q 20 --trim_front1 13 --detect_adapter_for_pe --dont_eval_duplication --trim_poly_g --trim_poly_x"
  picard:
    java_opts: "-Xmx4g"
    markduplicates:
      extra_args: ""
  deeptools:
    multiBamSummary:
      extra_args: "--binSize 10000"
    plotCorrelation:
      extra_args: "-p heatmap --corMethod spearman --skipZeros"
    bamCoverage:
      normalize_using: "RPKM"
      extra_args: "--binSize 10"
  gene_body_coverage:
    enabled: false
    refgene_bed: "path/dummy.bed"
    minimum_length: 100
    format: "pdf"
